
networks:
  openproject_network:
    driver: bridge

services:
  memcached:
    image: memcached:latest
    container_name: memcached_container
    restart: always
    ports:
      - "11211:11211"
    networks:
      - openproject_network

  openproject:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openproject_app
    restart: always
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_ENV: "production"
      MEMCACHE_SERVERS: "memcached:11211"
      OPENPROJECT_HTTPS: "false"
      MIGRATE_DB: "yes"       
      PRECOMPILE_ASSETS: "yes"
      CI: "false"
    depends_on:
      - memcached
    ports:
      - "3001:3000"
    networks:
      - openproject_network

